services:
  app:
    container_name: app
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql+aiopg://postgres:mysecretpassword@postgresql:5432/visitors
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    container_name: postgresql
    build: ./postgresql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=visitors
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5